# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will add a label to opened and reopened issues.

name: Label Issue

on:
  issues:
    types: [reopened, opened]

jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Set Issue Name
        uses: andymckay/labeler@1.04
        with:
            add-labels: "CI setup, bug"
            repo-token: ${{ secrets.GITHUB_TOKEN }}

          
      
